CREATE TABLE personas1 (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR (40), fecha DATE);

CREATE TABLE telefonos2 (numero CHAR (12), id_personas INT NOT NULL REFERENCES personas (id) ON DELETE CASCADE ON UPDATE CASCADE);